services:
  ros2_vscode_dev:
    container_name: ros2_vscode_dev
    image: ros2_vscode
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # network_mode: host
    environment:
      SDL_VIDEODRIVER: x11
      DISPLAY: $DISPLAY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/home/ubuntu/ws
    stdin_open: true
    privileged: true
    group_add:
      - video
    tty: true
    command: tail -f /dev/null
    restart: always
    ports:
      - 5184:5184
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [compute,utility,graphics,display]