
FROM althack/ros2:humble-cuda-gazebo-nvidia

ENV ROS_DISTRO=humble
ENV AMENT_PREFIX_PATH=/opt/ros/$ROS_DISTRO
ENV COLCON_PREFIX_PATH=/opt/ros/$ROS_DISTRO
ENV LD_LIBRARY_PATH=/opt/ros/$ROS_DISTRO/lib
ENV PATH=/opt/ros/$ROS_DISTRO/bin:$PATH
ENV PYTHONPATH=/opt/ros/$ROS_DISTRO/lib/python3.8/site-packages
ENV ROS_PYTHON_VERSION=3
ENV ROS_VERSION=2

ENV DEBIAN_FRONTEND=dialog
# Env vars for the nvidia-container-runtime.
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENV QT_X11_NO_MITSHM=1

# ENV DEBIAN_FRONTEND=noninteractive
RUN add-apt-repository ppa:kisak/kisak-mesa && apt-get update && apt-get install -y \
  # opengl stuff
  libgl1-mesa-glx \
  libgl1-mesa-dri \
  x11-apps \
  mesa-utils \
  libglvnd0 \
  libgl1 \
  libglx0 \
  libegl1 \
  libxext6 \
  libx11-6 \
  # other stuff
  inetutils-ping \
  net-tools \
  bash-completion \
  build-essential \
  cmake \
  gdb \
  git \
  git-lfs \
  tig \
  unzip \
  nano \
  gcc \
  cmake \
  libssl-dev \
  make \
  ninja-build \
  ranger \
  # pylint3
  python3-argcomplete \
  python3-colcon-common-extensions \
  python3-pip \
  python3-rosdep \
  python3-vcstool \
  vim \
  tmux \
  emacs \
  ranger \
  wget \
  gdbserver \
  htop \
  xterm \
  # joystick tools
  joystick \
  jstest-gtk \
  evtest \
  # Install ros distro testing packages
  ros-$ROS_DISTRO-ament-lint \
  ros-$ROS_DISTRO-launch-testing \
  ros-$ROS_DISTRO-launch-testing-ament-cmake \
  ros-$ROS_DISTRO-launch-testing-ros \
  ros-$ROS_DISTRO-rmw-cyclonedds-cpp \
  ros-${ROS_DISTRO}-nav2-mppi-controller \
  python3-autopep8 \
  && rm -rf /var/lib/apt/lists/* \
  && rosdep init || echo "rosdep already initialized"

ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG WORKSPACE=/home/$USERNAME

ENV DEPENDENCIES_WS /opt/dependencies_ws
RUN mkdir -p $DEPENDENCIES_WS/src

ENV HOME=/home/$USERNAME
ENV WS=$WORKSPACE

ARG CMAKE_BUILD_TYPE=RelWithDebInfo

# Build ROS 2 source dependencies
WORKDIR $DEPENDENCIES_WS
COPY ros_dependencies.repos ros_dependencies.repos
RUN vcs import src < ros_dependencies.repos
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    apt-get update && \
    rosdep update --rosdistro=$ROS_DISTRO && \
    rosdep install --rosdistro=$ROS_DISTRO -q -y --from-paths src --ignore-src && \
    rm -rf /var/likb/apt/lists/*

RUN . /opt/ros/$ROS_DISTRO/setup.sh && colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE

# Fix ros2 installation
RUN apt update && apt install -y ros-humble-rmw-cyclonedds-cpp

# Install PIP requirements
COPY requirements.txt /tmp/
RUN python3 -m pip install -r /tmp/requirements.txt

ENV DEBIAN_FRONTEND=dialog

# Add ros user to dialout to access usb devices (IMU for example)
# RUN usermod -a -G dialout ${USERNAME}

# Create source folder
WORKDIR $WS

# Install ros dependencies
COPY --chown=$USERNAME . src

RUN apt-get update && \
    . $DEPENDENCIES_WS/install/setup.sh && \
    rosdep update --rosdistro=$ROS_DISTRO && \
    rosdep install --rosdistro=$ROS_DISTRO --from-paths src --ignore-src -y && \
    rm -rf /var/lib/apt/lists/*

USER $USERNAME

RUN sudo chown -R ros .ros

# Build ros
RUN /bin/bash -c 'source $DEPENDENCIES_WS/install/setup.bash && cd /home/ros && colcon build --merge-install --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE'

RUN echo "if [ -f /home/ros/install/setup.bash ]; then source /home/ros/install/setup.bash; fi" >> /home/ros/.bashrc
RUN echo "if [ -f /usr/share/gazebo/setup.sh ]; then source /usr/share/gazebo/setup.sh; fi" >> /home/ros/.bashrc
RUN echo "export RCUTILS_COLORIZED_OUTPUT=1" >> /home/ros/.bashrc
RUN echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> /home/ros/.bashrc
# RUN echo "export FASTRTPS_DEFAULT_PROFILES_FILE=/home/ros/src/dds/dds_config_client.xml" >> /home/ros/.bashrc

RUN echo "alias dynobot_start=\"ros2 launch dynobot_bringup full.launch.py\"" >> /home/ros/.bashrc
RUN echo "alias dynobot_build=\"cd && colcon build --symlink-install --merge-install --cmake-args -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE && source /home/ros/install/setup.bash\"" >> /home/ros/.bashrc
