[package]
name = "rust_pubsub"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {version = "1", features = ["backtrace"]}
tokio = { version = "1.41.0", features = ["full"] }
tokio-util = { version = "0.7.12"}
tokio-stream = { version = "0.1"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "*"
futures-timer = "*"
thiserror = "2.0"
log = "0.4"
env_logger = "0.11"
toml = "0.8.19" 
mockall = "0.13.0"
glob = "0.3.1"
paste = "*"
rclrs = "*"
rosidl_runtime_rs = "*"
std_msgs = "*"
geometry_msgs = "*"
example_interfaces = "*"
rust_interfaces = "*"